version: '3'

services:
  web:
    build: .
    command: gunicorn blogapi.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


  